.TH randopitons "05 Nov. 2018" "ver 0.1"

.SH NAME
randopitons.sh - A script for downloading hitchiking files from https://randopitons.re.

.SH SYNOPSIS

.B randopitons.sh 
[ 
.B -lm / --list-maptype
] 
[
.B -lr / --list-regions
]

.B randopitons.sh 
[ 
.B -u / --username
"youremail@forrandopitons.re" ]

.B randopitons.sh 
[ 
.B -u / --username
"youremail@forrandopitons.re" ]
[
.B -r / --region
 "a region"]

.B randopitons.sh 
[ 
.B -u / --username
"youremail@forrandopitons.re" ]
[
.B -a / --all
]
[
.B -em / --elevator-music
]


.SH SYNOPSIS
.B randopitons.sh 
[ 
.B -u / --username
"youremail@forrandopitons.re" ]

.SH DESCRIPTION
You will need to make an account on the website before using the script.
The following regions are valid: cilaos, salazie, mafate, est, nord, ouest, sud, volcan, ailleurs. Case insensitive.
The elevator music need mpv and youtube-dl to be installed.

.SH AUTHORS
Lionel Miquel 
.B <lionel.miquel46@gmail.com>.
